# Generated by Django 4.1.3 on 2022-11-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_vagas_email'),
        ('vagas', '0002_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='vaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.vagas'),
        ),
    ]
